# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9002
baseurl:          /
url:              http://suitstrap.maartenvanhoof.be
encoding:         UTF-8

# Custom vars
current_version:  0.2.1
repo:             https://github.com/vanhoofmaarten/suitstrap

download_source:  https://github.com/vanhoofmaarten/vanhoofmaarten/archive/master.zip
